### ISSUE TITLE
HM-10 support for BLE

### ISSUE THREAD

**Issue by svanimisetti** [sieren/midimittr#19]
Thanks for this great project. I am a MIDI noob and am experimenting with some custom built midi controllers. One of my controllers uses a HM-10 bluetooth module. It seems to work fine on Windows 10. However, on iOS (both iPhone and iPad) - I have an issue connect the device to midimittr. I understand that HM-10 only allows 16-bit UUID and will not show up as a true BLE MIDI device on iOS.

I know others have created their own solutions by bridging BLE serial data from HM-10 with CoreMIDI. Is there a way that modules like HM-10 can be natively supported in midimittr without having to use a patch program? Or is this capability already present in midimittr.

**Comment by sieren** [comment]
midimittr uses Bluetooth MIDI as specified by the MMA. The app doesn't use any custom code or raw handling of MIDI/Bluetooth but only calls Apple's APIs (including the views provided by apple) for MIDI Setup.
Chances are, if it isn't working in midimittr, it wont work in any other iOS app either (eg. Garageband, which also offers Bluetooth MIDI)

**Comment by svanimisetti** [comment]
Thanks! If this being case - looks like the only option is to use a bridging app to push data over BLE serial to CoreMIDI (see a solution posted by [hoiberg ](https://github.com/hoiberg/bluetoothMidi/) on his project [Steinway](http://www.hangar42.nl/steinway))

**Comment by sieren** [comment]
Very likely. I did recall looking at the HM-10 many years ago as part of https://github.com/sieren/blidino and figured the inability to configure UUIDs properly according to standard was a no-go when implementing Arduino BLE-MIDI support. Kind of a shame. I dont know why they decided to limit this.

**Comment by svanimisetti** [comment]
I see that your blidino project is based on an nRF51822. The only other option (as I have the controller in my parts bin) is to use ESP32 as it supports 128-bit UUID and readily shows up as a BLE MIDI device. I wanted to use HM-10 as it was lying unused. I will attempt @hoiberg's method - and if all fails, I will eventually resort to ESP32. Thanks for your prompt response! Closing the issue.
