### ISSUE TITLE
Windows 10 issue with new iTunes version

### ISSUE THREAD

**Issue by svanimisetti** [sieren/midimittr#20]
I am unable to start midimittr after I update my iTunes version to 12.11.3.17. See attached screenshot. It appears that midimittr is unable to work with this version of iTunes. I saw notes on the download page regarding special version for 12.1. Is there a special version for 12.11.

![SharedScreenshot](https://user-images.githubusercontent.com/5341040/123283266-3ceba500-d4d9-11eb-8b10-9e984240a147.png)

**Comment by sieren** [comment]
I'm not sure as I haven't used Windows in a while. You need a 32 bit version of iTunes for midimittr to work on Windows.

**Comment by svanimisetti** [comment]
Ok. Thanks - I think I had 64-bit. I will try to install 32-bit and report back observations.

**Comment by svanimisetti** [comment]
Just downloaded and tried to install 32-bit iTunes - and as expected it fails to install. I guess I am closing this route of investigation as its not worth the effort.

**Comment by zeplissken** [comment]
hello ! did someone found a way to make it recognize itunes ? it is so frustrating to have the free solution to send midi to windows and be blocked by this issue...

**Comment by raidmarji** [comment]
Did nit find any version of iTunes 32 bit to work with windows 10. Any workaround?

**Comment by zeplissken** [comment]
no, couldn't make it work :( but i found another app to connect with : studiomux, you have to install the server on your computer and the app on your IOS, it works fine for me ! ;)

**Comment by raidmarji** [comment]
Thanx, I’ll buy the Studiomux and try it. I want to use GeoShred from iPad as midi controller for my pc :)

**Comment by raidmarji** [comment]
> no, couldn't make it work :( but i found another app to connect with : studiomux, you have to install the server on your computer and the app on your IOS, it works fine for me ! ;)

Can you explain how does it work for you? I bought it

**Comment by zeplissken** [comment]
download the server here : https://zerodebug.com/#/beta
install it on your computer, install the app on your ipad then just connect with a cable your ipad to your computer.
launch the server on your computer
launch the app on ipad
launch Geoshred, the studiomux app will recognize it as midi source
in geoshred use the midi output settings to send midi out and you are done !
there are vst plugin from studiomux which are instruments to put in your DAW but for me it is working without using them !
good luck !
